name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile
        uses: xu-cheng/texlive-action@v3
        with:
          texlive_version: latest
          os: alpine
          scheme: small
          run: |
            tlmgr install   \
              datetime2     \
              easylist      \
              enumitem      \
              ifoddpage     \
              tikzpagenodes \
              titlesec      \
              titling
            apk add make
            make

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
